sudo: required
sevices:
  - docker

before_install:
  - docker build -t taylone/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run docker run -e CI=true taylone/react-test npm test -- --coverage

after_success:
  - docker build -t taylone/multi-client ./client
  - docker build -t taylone/multi-nginx ./nginx
  - docker build -t taylone/multi-server ./server
  - docker build -t taylone/multi-worker ./worker
